# Site settings
title: PIP
description: "// PIP festudlejning af fester //"
email: artist@email

# Build settings
markdown: kramdown
permalink: pretty

port: 9000

sass:
  sass_dir: assets/css
  style: :compressed